language: node_js
node_js:
- '0.10'
env:
  global:
  # SAUCE_USERNAME
  - secure: T/TQF2JDzdaw5jmPsDnM+CXZJIncPSOj3qPevrzURP/g2+gEj0ogHjr86IKhDGNyNNyJIdKQCiy5pKFFqy8UkA6HFQ71SgRqtR+Kn/4httW5ZcouBRJMNuGXdJ8ORu+C2PLv/IwqVnGK8ECYv+0nrl9LIXXA6Skzkqj68U24FbY=
  # SAUCE_ACCESS_KEY
  - secure: dhei8bL0TYLt3bbOUJh371vpecrOwlrIlHEVcck8HyjIWK8g+ADvfjYy73YH2ZXJnzQNXpn6qitUtB3UK1hypvMeBKV7RTb1ZPUqMrrpgN5nsgumeb5RHClZc7U7YJSRNB/aZmJqAtTPthgsbFaNEIfYCigA/F64OlQfWN73Pwc=
  # COVERALLS_REPO_TOKEN
  - secure: JM0OBdfgqyjEEDG+Nhia/3fO7F1kqiITXQcNpjqOerMCg0C5QsXPHbS23pW5CcwiWeDR7IrHGKZCFUO1moexxFIAYV8oWDzSsnSW1nraQ1gr9MYMkTDQqNfvLZL3MiiMkywJ7ORBeBUYztLkheX/QA6MCUSqcgQnIOrMf8HraYc=
  - COVERALLS_SERVICE_NAME=travis-ci

branches:
  only:
    - master

after_script: ./utils/transform-coverage.js dist/scripts/all.js.map lcov.info | ./node_modules/coveralls/bin/coveralls.js
